// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'goBack': string;
  'story': string;
  'story__header': string;
}
export const cssExports: CssExports;
export default cssExports;
